spring:
  cloud:
    aws:
      parameterstore:
        enabled: true
        prefix: /flint/prod
        name: batch
        profile-separator: _
      region:
        static: ap-northeast-2

  jpa:
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:batch-schema-mysql.sql
    job:
      enabled: false

  security:
    user:
      name: ${BATCH_ADMIN_USER}
      password: ${BATCH_ADMIN_PASSWORD}

logging:
  level:
    kr.flint: info

flint:
  batch:
    scheduling:
      enabled: false

tmdb:
  base-url: ${TMDB_BASE_URL:https://api.themoviedb.org}
  api-key: ${TMDB_API_KEY}
