spring:
  datasource:
    url: ${prod.db.url}
    username: ${prod.db.username}
    password: ${prod.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false

decorator:
  datasource:
    p6spy:
      enable-logging: false

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      region: ${S3_REGION:ap-northeast-2}
      presign-expiration: 10m

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1h
  refresh-expiration: 14d
  temp-expiration: 30m

oauth:
  kakao:
    user-info-url: https://kapi.kakao.com/v2/user/me

logging:
  level:
    kr.flint: info