plugins {
    id 'org.springframework.boot'
}

bootJar {
    archiveBaseName = 'flint-admin-api'
}

bootBuildImage {
    environment = [
        'BP_JVM_VERSION': '21'
    ]
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.batch:spring-batch-integration'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    runtimeOnly 'com.mysql:mysql-connector-j'
    runtimeOnly 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.12.1'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    implementation project(':modules:shared')
    implementation project(':modules:user')
    implementation project(':modules:auth')
    implementation project(':modules:terms')
	    implementation project(':modules:content')
	    implementation project(':modules:collection')
	    implementation project(':modules:moderation')
	    implementation project(':modules:ott')

    implementation project(':infra:aws')
    implementation project(':infra:redis')
    implementation project(':infra:storage')
    implementation project(':infra:tmdb')

    implementation project(':apps:batch')
}
