plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation platform("org.springframework.ai:spring-ai-bom:1.1.2")

    //spring AI
    implementation "org.springframework.ai:spring-ai-starter-model-openai"
    implementation 'org.springframework.boot:spring-boot-starter'

    compileOnly 'org.jspecify:jspecify:1.0.0'
}
