spring:
  application:
    name: flint-admin-api

  config:
    import:
      - optional:file:.env[.properties]

  threads:
    virtual:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 100

  jackson:
    default-property-inclusion: non_null

  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:batch-schema-mysql.sql
    job:
      enabled: false

server:
  port: 8081
  shutdown: graceful
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never

decorator:
  datasource:
    p6spy:
      enable-logging: false
      multiline: true
      logging: slf4j

flint:
  batch:
    scheduling:
      enabled: false
    tmdb:
      export-base-url: https://files.tmdb.org/p/exports
      download-dir: ${java.io.tmpdir}/flint-tmdb-exports
      chunk-size: 100
      concurrency-limit: 50
      retry-attempts: 3
      retry-back-off-ms: 2000
