dependencies {
    implementation project(':modules:shared')
    implementation project(':infra:redis')

    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    testImplementation 'com.squareup.okhttp3:mockwebserver:4.12.0'
}
