plugins {
    id 'java-library'
}

dependencies {
    api 'org.springframework.cloud:spring-cloud-starter-openfeign'
    api 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    compileOnly 'org.jspecify:jspecify:1.0.0'
    annotationProcessor 'org.jspecify:jspecify:1.0.0'
}
